name: StackTodo.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    

    - name: Set environment variables
      run: |
        echo "TODOUSEREMAIL1=${{ secrets.TODOUSEREMAIL1 }}" >> $GITHUB_ENV
        echo "TODOUSERNAME1=${{ secrets.TODOUSERNAME1 }}" >> $GITHUB_ENV
        echo "TODOUSERNAME2=${{ secrets.TODOUSERNAME2 }}" >> $GITHUB_ENV
        echo "TODOPASS1=${{ secrets.TODOPASS1 }}" >> $GITHUB_ENV
        echo "TODOPASS2=${{ secrets.TODOPASS2 }}" >> $GITHUB_ENV

    - run: npm ci
    - run: npm run build --if-present
    - run: npm run smoke
